language:
- cpp
services:
- docker
matrix:
  include:
  - name: LLVM 7 Release
    env: LLVM_VERSION=7 DOCKER_BASE=disco BUILD_TYPE=release
script:
- ssh $BUILD_CLUSTER "cd /tmp/travis/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/bpftrace
  && LLVM_VERSION=${LLVM_VERSION} DOCKER_BASE=${DOCKER_BASE} BUILD_TYPE=${BUILD_TYPE}
  RUN_ALL_TESTS=1 ./build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_620a1b912f5c_key -iv $encrypted_620a1b912f5c_iv
  -in secrets.tar.enc -out ./secrets.tar -d
- mkdir -p ~/.ssh/
- tar xvf secrets.tar
- mv knonw_hosts ~/.ssh/known_hosts
- mv bpftrace_rsa ~/.ssh/id_rsa
- ssh $BUILD_CLUSTER mkdir -p /tmp/travis/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}
- rsync --recursive $(pwd) $BUILD_CLUSTER:/tmp/travis/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}
env:
  global:
    secure: jsCEinc/q/yIR2gclZGuteJLxCZbnzQMGLzM0fP63lDPL5QHb6nEUbpQbGu3l/pd4GRSYQUwu3PEbiW8Rm2O2wi+wUES8jXEPwaorjotfqj0mw4cg3fqJzTwrxEAQHNXj+OZiNw+5EKWkxdylHS7/rAaP/KAIWNEZvQIHIp+iP2qujG8AmP4zC1ieLtxxu1CmVaNJ67a338xHnyZ/3lDe+ciuRkONqV3EFyWp00i9hHrRxiPX6QDqXYlcZoDwzKHqOARdbKRUFA/2d/w4F99XTtS9zejEYK4IWo7juQmgbB90oqlGbrC0PwKLsDqCsYEz/hU3eG2c3uq1sglT2oXuWJy/uNt/zHPzt/ca5KXhGGbGnl0zgepp2C5o6j+s54psOatd/o1XRTErOlW1800PAw9QymwnWy+wE8dCdJfB9ka70pPH0xhdGJB2CROaOBI8O+JEDcRXgLnKbOcao3f4dsDJJ3Nyt8sqziRbt2YKvBP0oUhJssDO2bGf4yRT5LxfrccxoPZbZ1IE19G/di46gpzbGc3iPN6lK1HclODYCJ0/hS8St1aebxrF+1vjZa3muKQXyedaKi5vqFvy5eRQ0yNjMdR3/zX2jp7AghIfcf5es901oUwCZjegV9uhY0VNixQOAahFd4Q6eA3nn7uosYyrSYhP3qIzKxPe3DnWZQ=
